"use client";
import { useEffect, useState } from "react";
import type { Lead, LeadStatus, Project } from "@/lib/types";

export function AdminDashboard() {
  const [leads, setLeads] = useState<Lead[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetch("/api/leads"), fetch("/api/projects")]).then(async ([leadResponse, projectResponse]) => { if (!leadResponse.ok) throw new Error("Couldn’t load dashboard data."); setLeads(await leadResponse.json()); setProjects(await projectResponse.json()); }).catch((err) => setError(err.message)); }, []);
  async function changeStatus(id: string, status: LeadStatus) { const response = await fetch(`/api/leads/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (response.ok) setLeads((items) => items.map((lead) => lead.id === id ? { ...lead, status } : lead)); }
  return <div className="admin-dashboard"><header><div><p className="eyebrow">iCodeee control room</p><h1>GOOD TO SEE<br />YOU <span>BUILDING.</span></h1></div><a href="/" target="_blank" rel="noreferrer" className="admin-link">View site ↗</a></header>{error && <p className="form-error">{error}</p>}<section><div className="admin-section-title"><h2>Leads</h2><span>{leads.length} total</span></div><div className="lead-table">{leads.length ? leads.map((lead) => <article key={lead.id}><div><strong>{lead.name}</strong><a href={`mailto:${lead.email}`}>{lead.email}</a></div><p>{lead.company || "Independent"}<br /><span>{lead.project_type || "No focus selected"} · {lead.budget || "Budget not set"}</span></p><p className="lead-message">{lead.message}</p><select value={lead.status} onChange={(event) => changeStatus(lead.id, event.target.value as LeadStatus)} aria-label={`Update ${lead.name} status`}>{["NEW", "CONTACTED", "QUALIFIED", "CLOSED", "ARCHIVED"].map((status) => <option key={status}>{status}</option>)}</select></article>) : <p className="admin-empty">No leads yet.</p>}</div></section><section><div className="admin-section-title"><h2>Projects</h2><span>{projects.length} in CMS</span></div><p className="admin-empty">Project records are available through the protected API. Add the approved Slugsera and Rupali Construction details, images, live URLs and case-study copy in Supabase to publish them.</p></section></div>;
}
