"use client";

import { useState } from "react";

const initial = { name: "", email: "", phone: "", company: "", website: "", project_type: "", budget: "", message: "", company_site: "" };
export function ContactForm() {
  const [form, setForm] = useState(initial); const [state, setState] = useState<"idle" | "sending" | "sent" | "error">("idle"); const [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setState("sending"); setError(""); try { const response = await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "We couldn’t send your message."); setState("sent"); setForm(initial); } catch (err) { setError(err instanceof Error ? err.message : "Something went wrong."); setState("error"); } }
  const update = (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setForm({ ...form, [event.target.name]: event.target.value });
  if (state === "sent") return <div className="form-success" role="status"><p className="eyebrow">Message received</p><h2>WE&apos;LL BE IN<br /><span>TOUCH.</span></h2><p>Thanks for sharing the brief. We&apos;ll review it and reply soon.</p><button className="button" onClick={() => setState("idle")}>Send another <span>→</span></button></div>;
  return <form className="contact-form" onSubmit={submit}><div className="honeypot" aria-hidden="true"><label>Leave this empty<input tabIndex={-1} autoComplete="off" name="company_site" value={form.company_site} onChange={update} /></label></div><div className="form-grid"><Field label="Name" name="name" value={form.name} update={update} required /><Field label="Email" name="email" type="email" value={form.email} update={update} required /><Field label="Phone" name="phone" type="tel" value={form.phone} update={update} /><Field label="Company" name="company" value={form.company} update={update} /><Field label="Website" name="website" type="url" value={form.website} update={update} placeholder="https://" /><label>What are you building?<select name="project_type" value={form.project_type} onChange={update}><option value="">Choose a focus</option><option>Brand identity</option><option>Website or web product</option><option>Ecommerce store</option><option>UI / UX design</option><option>Content strategy</option><option>Graphic design</option><option>Something else</option></select></label><label>Indicative budget<select name="budget" value={form.budget} onChange={update}><option value="">Choose a range</option><option>Under ₹1L</option><option>₹1L–₹3L</option><option>₹3L–₹8L</option><option>₹8L+</option></select></label></div><label className="message-field">What&apos;s the opportunity?<textarea name="message" value={form.message} onChange={update} minLength={20} required placeholder="Tell us what you’re building, where it needs to go, and what matters most." /></label>{state === "error" && <p className="form-error" role="alert">{error}</p>}<button className="button" disabled={state === "sending"}>{state === "sending" ? "Sending…" : "Send the brief"}<span>→</span></button></form>;
}
function Field({ label, name, value, update, type = "text", required = false, placeholder }: { label: string; name: string; value: string; update: (event: React.ChangeEvent<HTMLInputElement>) => void; type?: string; required?: boolean; placeholder?: string }) { return <label>{label}<input name={name} type={type} value={value} onChange={update} required={required} placeholder={placeholder} /></label>; }

